# Generated by Django 3.2.9 on 2021-12-06 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_msg_authur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='msg_authur',
            new_name='comment_authur',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='msg_text',
            new_name='comment_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_on',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
    ]
