# Generated by Django 3.2.9 on 2021-12-06 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211206_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_sended',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
