# Generated by Django 4.0 on 2022-01-01 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_replypostcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='authur',
            new_name='author',
        ),
    ]
