# Generated by Django 4.0 on 2022-01-01 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_authur_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replypostcomments',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment'),
        ),
    ]
